/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.util.ArrayList;
import modelo.Empleado;
import java.awt.Color;
/**
 *
 * @author david
 */
public class frm_empleado extends javax.swing.JFrame {

    /**
     * Creates new form frm_empleado
     */
Empleado obj_empleado;
    public frm_empleado() {
        initComponents();
        obj_empleado = new Empleado();
        try{
        ArrayList<String> lista = new ArrayList<>();
        lista = obj_empleado.llenar();
        for (int i = 0; i<lista.size(); i++){
            cmb_puesto.addItem(lista.get(i));
        }
        }catch(Exception ex){
            System.out.println("Error..."+ex.getMessage());
        } 
        tbl_empleado.setModel(obj_empleado.mostrar());
        btn_aceptar.setEnabled(false);
        btn_modificar.setEnabled(false);
        btn_eliminar.setEnabled(false);
    }
    
    public void validar(){
        if(txt_codigo.getText().isEmpty()){
            error_codigo.setText("Obligatorio");
        }else{
            error_codigo.setText("");
        }
        if(txt_nombre.getText().isEmpty()){
            error_nombres.setText("Obligatorio");
        }else{
            error_nombres.setText("");
        }
        if(txt_apellido.getText().isEmpty()){
            error_apellidos.setText("Obligatorio");
        }else{
            error_apellidos.setText("");
        }
        if(txt_direccion.getText().isEmpty()){
            error_direccion.setText("Obligatorio");
        }else{
            error_direccion.setText("");
        }
        if(txt_telefono.getText().isEmpty()){
            error_telefono.setText("Obligatorio");
        }else{
            error_telefono.setText("");
        }
        if(txt_fNacimiento.getText().isEmpty()){
            error_fNacimiento.setText("Obligatorio");
        }else{
            error_fNacimiento.setText("");
        }
        
        if(txt_codigo.getText().isEmpty()||lbl_codigo.getText().equals("Error (J###)")||txt_nombre.getText().isEmpty()
                ||lbl_nombres.getText().equals("Error en nombres")||txt_apellido.getText().isEmpty()||lbl_nombres.getText().equals("Error apellidos")
                ||txt_direccion.getText().isEmpty()||txt_telefono.getText().isEmpty()||lbl_telefono.getText().equals("Error en telefono")
                ||txt_fNacimiento.getText().isEmpty()||lbl_fNacimiento.getText().equals("Error en FN")){
            btn_aceptar.setEnabled(false);
            btn_modificar.setEnabled(false);
            btn_eliminar.setEnabled(false);
            lbl_aviso.setForeground(Color.red);
            lbl_aviso.setText("<html>Llene los campos correctamente para habilitar los botones<html>");
        }
        else{
            btn_aceptar.setEnabled(true);
            btn_modificar.setEnabled(true);
            btn_eliminar.setEnabled(true);
            lbl_aviso.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_codigo = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        lbl_puesto = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        lbl_apellidos = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        lbl_fNacimiento = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_fNacimiento = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        lbl_etiquetaid = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        cmb_puesto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_empleado = new javax.swing.JTable();
        error_codigo = new javax.swing.JLabel();
        error_nombres = new javax.swing.JLabel();
        error_apellidos = new javax.swing.JLabel();
        error_direccion = new javax.swing.JLabel();
        error_telefono = new javax.swing.JLabel();
        error_fNacimiento = new javax.swing.JLabel();
        lbl_aviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(173, 216, 230));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(135, 206, 235));
        jPanel1.setToolTipText("");

        lbl_codigo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_codigo.setText("Codigo");

        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_codigoKeyReleased(evt);
            }
        });

        lbl_puesto.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_puesto.setText("Puesto");

        lbl_nombres.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_nombres.setText("Nombres");

        lbl_apellidos.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_apellidos.setText("Apellidos");

        lbl_direccion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_direccion.setText("Direccion");

        lbl_telefono.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_telefono.setText("Telefono");
        lbl_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_telefonoKeyReleased(evt);
            }
        });

        lbl_fNacimiento.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_fNacimiento.setText("Fecha de nacimiento");

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombreKeyReleased(evt);
            }
        });

        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyReleased(evt);
            }
        });

        txt_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_direccionKeyReleased(evt);
            }
        });

        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyReleased(evt);
            }
        });

        txt_fNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fNacimientoKeyReleased(evt);
            }
        });

        btn_aceptar.setBackground(new java.awt.Color(124, 252, 0));
        btn_aceptar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_modificar.setBackground(new java.awt.Color(255, 140, 0));
        btn_modificar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_modificar.setText("Actualizar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(139, 0, 0));
        btn_eliminar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        lbl_etiquetaid.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_etiquetaid.setText("Id");

        lbl_id.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_id.setText("0");

        cmb_puesto.setBackground(new java.awt.Color(0, 0, 0));
        cmb_puesto.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cmb_puesto.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setToolTipText("");
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tbl_empleado.setBackground(new java.awt.Color(102, 102, 102));
        tbl_empleado.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tbl_empleado.setForeground(new java.awt.Color(255, 255, 255));
        tbl_empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_empleado.setSelectionBackground(new java.awt.Color(255, 102, 0));
        tbl_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_empleadoMouseClicked(evt);
            }
        });
        tbl_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_empleadoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_empleado);

        error_codigo.setForeground(new java.awt.Color(255, 0, 0));

        error_nombres.setForeground(new java.awt.Color(255, 0, 0));

        error_apellidos.setForeground(new java.awt.Color(255, 0, 0));

        error_direccion.setForeground(new java.awt.Color(255, 0, 0));

        error_telefono.setForeground(new java.awt.Color(255, 0, 0));

        error_fNacimiento.setForeground(new java.awt.Color(255, 0, 0));

        lbl_aviso.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fNacimiento)
                            .addComponent(lbl_telefono)
                            .addComponent(lbl_direccion)
                            .addComponent(lbl_apellidos)
                            .addComponent(lbl_nombres)
                            .addComponent(lbl_puesto)
                            .addComponent(lbl_codigo)
                            .addComponent(lbl_etiquetaid))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(error_nombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cmb_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(error_apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(error_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(error_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_fNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(error_fNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(error_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_aviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_eliminar)
                        .addGap(35, 35, 35)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(lbl_etiquetaid))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_codigo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_codigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_puesto)
                    .addComponent(cmb_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombres, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_nombres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_apellidos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_apellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_direccion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_direccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_telefono, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fNacimiento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_fNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(error_fNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_eliminar)
                            .addComponent(btn_aceptar)
                            .addComponent(btn_modificar))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tbl_empleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_empleadoKeyReleased
        // TODO add your handling code here:
        selec_datos();
        if (txt_codigo.getText().matches("[J]{1}[0-9]{3}")){
            lbl_codigo.setForeground(Color.black);
            lbl_codigo.setText("Codigo");
        }else{
            lbl_codigo.setForeground(Color.red);
            lbl_codigo.setText("Error (J###)");
        }
        if(txt_nombre.getText().matches("[A-Z]{1}[a-z]{2,9}([ ][A-Z]{1}[a-z]{2,9})?")){
            lbl_nombres.setForeground(Color.black);
            lbl_nombres.setText("Nombres");
        }else{
            lbl_nombres.setForeground(Color.red);
            lbl_nombres.setText("Error en nombres");
        }
        if(txt_apellido.getText().matches("[A-Z]{1}[a-z]{2,9}([ ][A-Z]{1}[a-z]{2,9})?")){
            lbl_apellidos.setForeground(Color.black);
            lbl_apellidos.setText("Apellido");
            
        }else{
            lbl_apellidos.setForeground(Color.red);
            lbl_apellidos.setText("Error en apellidos");
        }
        if(txt_telefono.getText().matches("[0-9]{8}")){
            lbl_telefono.setForeground(Color.black);
            lbl_telefono.setText("Telefono");
        }else{
            lbl_telefono.setForeground(Color.red);
            lbl_telefono.setText("Error en telefono");
        }
        if(txt_fNacimiento.getText().matches("[0-9]{4}[-]{1}[0-1]{1}[0-9]{1}[-]{1}[0-3]{1}[0-9]{1}")){
            lbl_fNacimiento.setForeground(Color.black);
            lbl_fNacimiento.setText("Fecha de nacimiento");
        }else{
            lbl_fNacimiento.setForeground(Color.red);
            lbl_fNacimiento.setText("Error en FN");
        }
        validar();
    }//GEN-LAST:event_tbl_empleadoKeyReleased

    private void tbl_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_empleadoMouseClicked
        // TODO add your handling code here:
        selec_datos();
        if (txt_codigo.getText().matches("[J]{1}[0-9]{3}")){
            lbl_codigo.setForeground(Color.black);
            lbl_codigo.setText("Codigo");
        }else{
            lbl_codigo.setForeground(Color.red);
            lbl_codigo.setText("Error (J###)");
        }
        if(txt_nombre.getText().matches("[A-Z]{1}[a-z]{2,9}([ ][A-Z]{1}[a-z]{2,9})?")){
            lbl_nombres.setForeground(Color.black);
            lbl_nombres.setText("Nombres");
        }else{
            lbl_nombres.setForeground(Color.red);
            lbl_nombres.setText("Error en nombres");
        }
        if(txt_apellido.getText().matches("[A-Z]{1}[a-z]{2,9}([ ][A-Z]{1}[a-z]{2,9})?")){
            lbl_apellidos.setForeground(Color.black);
            lbl_apellidos.setText("Apellido");
            
        }else{
            lbl_apellidos.setForeground(Color.red);
            lbl_apellidos.setText("Error en apellidos");
        }
        if(txt_telefono.getText().matches("[0-9]{8}")){
            lbl_telefono.setForeground(Color.black);
            lbl_telefono.setText("Telefono");
        }else{
            lbl_telefono.setForeground(Color.red);
            lbl_telefono.setText("Error en telefono");
        }
        if(txt_fNacimiento.getText().matches("[0-9]{4}[-]{1}[0-1]{1}[0-9]{1}[-]{1}[0-3]{1}[0-9]{1}")){
            lbl_fNacimiento.setForeground(Color.black);
            lbl_fNacimiento.setText("Fecha de nacimiento");
        }else{
            lbl_fNacimiento.setForeground(Color.red);
            lbl_fNacimiento.setText("Error en FN");
        }
        validar();
    }//GEN-LAST:event_tbl_empleadoMouseClicked

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        obj_empleado = new Empleado();
        obj_empleado.setId(Integer.valueOf(lbl_id.getText()));
        obj_empleado.eliminar();
        tbl_empleado.setModel(obj_empleado.mostrar());
        lbl_id.setText("0");
        txt_codigo.setText("");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_direccion.setText("");
        txt_telefono.setText("");
        txt_fNacimiento.setText("");
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        String puesto = cmb_puesto.getSelectedItem().toString();
        obj_empleado = new Empleado(Integer.valueOf(lbl_id.getText()),txt_codigo.getText(),puesto,txt_nombre.getText(),txt_apellido.getText(),txt_direccion.getText(),txt_telefono.getText(),txt_fNacimiento.getText());
        obj_empleado.actualizar();
        tbl_empleado.setModel(obj_empleado.mostrar());
        lbl_id.setText("0");
        txt_codigo.setText("");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_direccion.setText("");
        txt_telefono.setText("");
        txt_fNacimiento.setText("");
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        String puesto = cmb_puesto.getSelectedItem().toString();
        obj_empleado = new Empleado(0,txt_codigo.getText(),puesto,txt_nombre.getText(),txt_apellido.getText(),txt_direccion.getText(),txt_telefono.getText(),txt_fNacimiento.getText());
        obj_empleado.agregar();
        tbl_empleado.setModel(obj_empleado.mostrar());
        txt_codigo.setText("");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_direccion.setText("");
        txt_telefono.setText("");
        txt_fNacimiento.setText("");
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void txt_codigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyReleased
        // TODO add your handling code here:
        if (txt_codigo.getText().matches("[J]{1}[0-9]{3}")){
            lbl_codigo.setForeground(Color.black);
            lbl_codigo.setText("Codigo");
        }else{
            lbl_codigo.setForeground(Color.red);
            lbl_codigo.setText("Error (J###)");
        }
        validar();
    }//GEN-LAST:event_txt_codigoKeyReleased

    private void txt_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyReleased
        // TODO add your handling code here:
        if(txt_nombre.getText().matches("[A-Z]{1}[a-z]{2,9}([ ][A-Z]{1}[a-z]{2,9})?")){
            lbl_nombres.setForeground(Color.black);
            lbl_nombres.setText("Nombres");
        }else{
            lbl_nombres.setForeground(Color.red);
            lbl_nombres.setText("Error en nombres");
        }
        validar();
    }//GEN-LAST:event_txt_nombreKeyReleased

    private void txt_apellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyReleased
        // TODO add your handling code here:
        if(txt_apellido.getText().matches("[A-Z]{1}[a-z]{2,9}([ ][A-Z]{1}[a-z]{2,9})?")){
            lbl_apellidos.setForeground(Color.black);
            lbl_apellidos.setText("Apellido");
            
        }else{
            lbl_apellidos.setForeground(Color.red);
            lbl_apellidos.setText("Error en apellidos");
        }
        validar();
    }//GEN-LAST:event_txt_apellidoKeyReleased

    private void lbl_telefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_telefonoKeyReleased
        // TODO add your handling code here:   
    }//GEN-LAST:event_lbl_telefonoKeyReleased

    private void txt_telefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyReleased
        // TODO add your handling code here:
        if(txt_telefono.getText().matches("[0-9]{8}")){
            lbl_telefono.setForeground(Color.black);
            lbl_telefono.setText("Telefono");
        }else{
            lbl_telefono.setForeground(Color.red);
            lbl_telefono.setText("Error en telefono");
        }
        validar();
    }//GEN-LAST:event_txt_telefonoKeyReleased

    private void txt_fNacimientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fNacimientoKeyReleased
        // TODO add your handling code here:
        if(txt_fNacimiento.getText().matches("[0-9]{4}[-]{1}[0-1]{1}[0-9]{1}[-]{1}[0-3]{1}[0-9]{1}")){
            lbl_fNacimiento.setForeground(Color.black);
            lbl_fNacimiento.setText("Fecha de nacimiento");
        }else{
            lbl_fNacimiento.setForeground(Color.red);
            lbl_fNacimiento.setText("Error en FN");
        }
        validar();
    }//GEN-LAST:event_txt_fNacimientoKeyReleased

    private void txt_direccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txt_direccionKeyReleased

    public void selec_datos(){
        int fila = tbl_empleado.getSelectedRow();
        lbl_id.setText(tbl_empleado.getValueAt(fila,0).toString());
        txt_codigo.setText(tbl_empleado.getValueAt(fila,1).toString());
        cmb_puesto.setSelectedItem(tbl_empleado.getValueAt(fila,7).toString());
        txt_nombre.setText(tbl_empleado.getValueAt(fila,2).toString());
        txt_apellido.setText(tbl_empleado.getValueAt(fila,3).toString());
        txt_direccion.setText(tbl_empleado.getValueAt(fila,4).toString());
        txt_telefono.setText(tbl_empleado.getValueAt(fila,5).toString());
        txt_fNacimiento.setText(tbl_empleado.getValueAt(fila,6).toString());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> cmb_puesto;
    private javax.swing.JLabel error_apellidos;
    private javax.swing.JLabel error_codigo;
    private javax.swing.JLabel error_direccion;
    private javax.swing.JLabel error_fNacimiento;
    private javax.swing.JLabel error_nombres;
    private javax.swing.JLabel error_telefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_aviso;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_etiquetaid;
    private javax.swing.JLabel lbl_fNacimiento;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_puesto;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JTable tbl_empleado;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_fNacimiento;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
